"""add match_count and last_match_time to keywords

Revision ID: 66d164fbec6e
Revises: 142b0dc3f0c4
Create Date: 2025-04-01 20:28:00.077097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66d164fbec6e'
down_revision: Union[str, None] = '142b0dc3f0c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keywords', sa.Column('match_count', sa.Integer(), nullable=True))
    op.add_column('keywords', sa.Column('last_match_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keywords', 'last_match_time')
    op.drop_column('keywords', 'match_count')
    # ### end Alembic commands ###
