"""add risk_level and is_active to keywords

Revision ID: 69c73476786f
Revises: f69514dd8505
Create Date: 2025-04-01 17:27:44.414317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69c73476786f'
down_revision: Union[str, None] = 'f69514dd8505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keywords', sa.Column('risk_level', sa.String(length=50), nullable=False))
    op.add_column('keywords', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keywords', 'is_active')
    op.drop_column('keywords', 'risk_level')
    # ### end Alembic commands ###
